Fixed bug in Controller when firing onChange for functions. Dart would throw noSuchMethodError when calling the onChange proxy function for dat.gui functions. Since functions can't change, the proxy should only be added when dealing with non-function properties